export const LETTERS = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ";

export const ACTIVITIES = [
  "A: Ver el Amanecer juntas",
  "B: Bailar en Buda Bar 🎶",
  "C: Comida Griga 🍓🧀",
  "D: Desayuno en la cama",
  "E: Escape Urbano: Pasear por barrios/Big Bug",
  "F: Fondue de Queso o Chocolate",
  "G: Game Night+ snack obligatorio 🍿",
  "H: Hobby Cafe",
  "I: Ir al cine",
  "J: Pijama Party",
  "K: Kopi Cafe",
  "L: Merienda en La Crew",
  "M: MUCHO Cafe de especialidad",
  "N: Noche tematica: Elegimos un Pais y cocinamos algo tipico",
  "Ñ: Ñoquis juntas✨",
  "O: Obras cortas",
  "P: Pulso Specialty",
  "Q: Quiz: 5 preguntas de pareja, la que gana elije el postre",
  "R: Recrear la primera vez que nos vimos (puede haber beso esta vez)💋",
  "S: Scape Room",
  "T: Tour de los Misterios",
  "U: Una Playlist nueva",
  "V: Vitraux y Vino",
  "W: Wine Night",
  "X: Noxxe Relaxxx",
  "Y: Yatai Yatoi",
  "Z: Pizza Party! Mini pizzas tematicas, cocinemos juntas"
];
